<?php

/**
 * Settings for plugin options page
 *
 * This is the file with settings for ItalyStrap options page
 *
 * @since 2.0.0
 *
 * @package ItalyStrap
 */

namespace ItalyStrap\Admin;

if (! defined('ITALYSTRAP_PLUGIN') or ! ITALYSTRAP_PLUGIN) {
    die();
}

use ItalyStrap\Core;

$wp_upload_dir = wp_upload_dir();

$beta = ' {{BETA VERSION}}';

return [
    /**
     * Plugin configuration array
     */
    'general'   => [
        'tab_title'         => __('General', 'italystrap'),
        'id'                => 'general',
        'title'             => __('General options page', 'italystrap'),
        // 'desc'               => __( 'General setting for ItalyStrap plugin', 'italystrap' ),
        'settings_fields'   => [
            [
                'id'        => 'activate_advanced',
                'title'     => __('Activate advanced options', 'italystrap'),
                'args'      => [
                    'label'         => __('Activate advanced options', 'italystrap') . $beta,
                    'desc'          => __('If you want to have more advanced options to control', 'italystrap'),
                    'id'            => 'activate_advanced',
                    'type'          => 'checkbox',
                    'class'         => 'activate_advanced easy hidden',
                    'default'       => '1',
                    // 'validate'   => 'ctype_alpha',
                    'sanitize'      => 'sanitize_text_field',
                ],
                // 'show_on'                => Core\is_beta(),
            ],
            [
                'id'        => 'show-ids',
                'title'     => __('Show Post Type IDs', 'italystrap'),
                'args'      => [
                    'label'         => __('Show Post Type IDs', 'italystrap'),
                    'desc'          => __('Post type edit screen: show post/page IDS', 'italystrap'),
                    'id'            => 'show-ids',
                    'type'          => 'checkbox',
                    'class'         => 'show-ids easy',
                    'default'       => '',
                    // 'validate'   => 'ctype_alpha',
                    'sanitize'      => 'sanitize_text_field',
                ],
            ],
            [
                'id'        => 'show-thumb',
                'title'     => __('Show Post Type Thumb', 'italystrap'),
                'args'      => [
                    'label'         => __('Show the Post Type Thumbnail', 'italystrap'),
                    'desc'          => __('Post type edit screen: show post/page thumbnail', 'italystrap'),
                    'id'            => 'show-thumb',
                    'type'          => 'checkbox',
                    'class'         => 'show-thumb easy',
                    'default'       => '',
                    // 'validate'   => 'ctype_alpha',
                    'sanitize'      => 'sanitize_text_field',
                ],
            ],
            [
                'id'        => 'kill-emojis',
                'title'     => __('Kill the Emojis', 'italystrap'),
                'args'      => [
                    'label'         => __('Kill the Emojis', 'italystrap'),
                    'desc'          => __('Avoid loading Emojis support if your does not need it to speed up the website.', 'italystrap'),
                    'id'            => 'kill-emojis',
                    'type'          => 'checkbox',
                    'class'         => 'kill-emojis easy',
                    'default'       => 'on',
                    // 'validate'   => 'ctype_alpha',
                    'sanitize'      => 'sanitize_text_field',
                ],
            ],
            [
                'id'        => 'activate_social_share',
                'title'     => __('Social Sharing Button', 'italystrap'),
                'args'      => [
                    'label'         => __('Activate Social Sharing Button', 'italystrap') . $beta,
                    'desc'          => __('This are a simple social sharing links', 'italystrap'),
                    'id'            => 'activate_social_share',
                    'type'          => 'checkbox',
                    'class'         => 'activate_social_share easy',
                    'default'       => '',
                    // 'validate'   => 'ctype_alpha',
                    'sanitize'      => 'sanitize_text_field',
                ],
                'show_on'               => Core\is_beta(),
            ],
            [
                'id'        => 'social_button_position',
                'title'     => __('Social Sharing Button position', 'italystrap'),
                'args'      => [
                    'desc'          => __('Select the position to display buttons', 'italystrap') . $beta,
                    'id'            => 'social_button_position',
                    'type'          => 'select',
                    'options'       => [
                        'before'    => __('Before the content', 'italystrap'),
                        'after'     => __('After the content', 'italystrap'),
                        'both'      => __('Before and after the content', 'italystrap'),
                    ],
                    'class'         => 'social_button_position easy',
                    'default'       => 'after',
                    // 'validate'   => 'ctype_alpha',
                    'sanitize'      => 'sanitize_text_field',
                ],
                'show_on'               => Core\is_beta(),
            ],
            [
                'id'        => 'social_button_on_post_types',
                'title'     => __('Display Social Sharing on', 'italystrap'),
                'args'      => [
                    'desc'          => __('Select the post types to display buttons', 'italystrap') . $beta,
                    'id'            => 'social_button_on_post_types',
                    'type'          => 'checkbox',
                    'options'       => (array) get_post_types(
                        [
                            'public'   => true,
                        ]
                    ),
                    'class'         => 'widefat post_types social_button_position easy',
                    'default'       => 'post',
                    // 'validate'   => 'ctype_alpha',
                    'sanitize'      => 'sanitize_select_multiple',
                ],
                'show_on'               => Core\is_beta(),
            ],
            [
                'id'        => 'google_api_key',
                'title'     => __('Google API Key', 'italystrap'),
                'args'      => [
                    'desc'          => __('Insert here the google API key.', 'italystrap') . $beta,
                    'id'            => 'google_api_key',
                    'type'          => 'text',
                    'class'         => 'google_api_key easy',
                    'default'       => '',
                    // 'validate'       => 'ctype_alpha',
                    'sanitize'      => 'sanitize_text_field',
                ],
                'show_on'               => Core\is_beta(),
            ],
            [
                'id'        => 'web_font_loading',
                'title'     => __('Web font Loading', 'italystrap'),
                'args'      => [
                    'label'         => __('Web font Loading', 'italystrap') . $beta,
                    'desc'          => __('Activate it for using the web fonts loader (lazyload for the web fonts), then you have to go to the <strong>customizer</strong> and select the font, weight and subsets you want to use in this site, then in the customizer below the selected font you can add in the dedicated text input the HTML tags or CSS selector you want to bind to the font selected, all separated by comma. Example: <code>body</code> or <code>h1</code> or <code>h1,h2,h3,h4,h5,h6</code> or <code>.widget-title</code>. Otherwise you can add some css to the Custom CSS area of this plugin (Settings > Style > Custom CSS) or in your style.css like this:
						<br>
						<pre>.fonts-loaded body{ font-family: "Open Sans"; }<br>.fonts-loaded h1{ font-family: "Lato"; }</pre>', 'italystrap'),
                    'id'            => 'web_font_loading',
                    'type'          => 'checkbox',
                    'class'         => 'web_font_loading hard',
                    'default'       => '',
                    // 'validate'   => 'ctype_alpha',
                    'sanitize'      => 'sanitize_text_field',
                ],
                'show_on'               => Core\is_beta(),
            ],
            [
                'id'        => 'visual_editor_on_terms',
                'title'     => __('Visual editor on terms', 'italystrap'),
                'args'      => [
                    'label'         => __('Display visual editor on term page', 'italystrap'),
                    'desc'          => __('(Cats, Tags and Custom terms)', 'italystrap'),
                    'id'            => 'visual_editor_on_terms',
                    'type'          => 'checkbox',
                    'class'         => 'visual_editor_on_terms easy',
                    'default'       => '',
                    // 'validate'   => 'ctype_alpha',
                    'sanitize'      => 'sanitize_text_field',
                ]
            ],
            [
                'id'        => 'show_theme_hooks',
                'title'     => __('Theme Hooks', 'italystrap'),
                'args'      => [
                    'label'         => __('Show Theme Hooks', 'italystrap'),
                    'desc'          => __('Only fof ItalyStrap theme framework. This is only for getting a visual of the ItalyStrap theme framework hooks registered.', 'italystrap'),
                    'id'            => 'show_theme_hooks',
                    'type'          => 'checkbox',
                    'class'         => 'show_theme_hooks easy',
                    'default'       => '',
                    // 'validate'       => 'ctype_alpha',
                    'sanitize'      => 'sanitize_text_field',
                ],
                'show_on'               => Core\is_italystrap_active(),
            ],
            [
                'id'        => 'show_hooked_callable',
                'title'     => __('Hooked callable', 'italystrap'),
                'args'      => [
                    'label'         => __('Show Hooked callable', 'italystrap'),
                    'desc'          => __('This will show callable with hook.', 'italystrap'),
                    'id'            => 'show_hooked_callable',
                    'type'          => 'checkbox',
                    'class'         => 'show_hooked_callable easy',
                    'default'       => '',
                    // 'validate'       => 'ctype_alpha',
                    'sanitize'      => 'sanitize_text_field',
                ],
                'show_on'               => Core\is_italystrap_active(),
            ],
            [
                'id'        => 'menu_cache',
                'title'     => __('Cache the menu output', 'italystrap'),
                'args'      => [
                    'label'         => __('Cache the menu output', 'italystrap') . $beta,
                    'desc'          => __('This will put in cache the menu output only if server cache is active.', 'italystrap'),
                    'id'            => 'menu_cache',
                    'type'          => 'checkbox',
                    'class'         => 'menu_cache easy',
                    'default'       => '1',
                    // 'validate'   => 'ctype_alpha',
                    'sanitize'      => 'sanitize_text_field',
                ],
                'show_on'               => Core\is_beta(),
            ],
        ],
    ],
    /**
     * This is the Widget configuration
     */
    'widget'    => [
        'tab_title'         => __('Widgets', 'italystrap'),
        'id'                => 'widget',
        'title'             => __('Options page for widgets', 'italystrap'),
        'desc'              => __('Select the widgets you want to use.', 'italystrap'),
        'settings_fields'   => [
            [
                'id'        => 'widget_areas',
                'title'     => __('Widget Areas', 'italystrap'),
                'args'      => [
                    'label'         => __('Activate new settings page for widget areas', 'italystrap') . $beta,
                    'desc'          => __('This will add new settings page on Appearance where you can create new widget area to append on theme action hook.', 'italystrap'),
                    'id'            => 'widget_areas',
                    'type'          => 'checkbox',
                    'class'         => 'widget_areas medium',
                    'default'       => '',
                    // 'validate'   => 'ctype_alpha',
                    'sanitize'      => 'sanitize_text_field',
                ],
                'show_on'               => Core\is_beta(),
            ],
            [
                'id'        => 'widget_visibility',
                'title'     => __('Widget Visibility', 'italystrap'),
                'args'      => [
                    'label'         => __('Add Widget Visibility to any widget.', 'italystrap'),
                    'desc'          => __('This will add the possibility to choice the widget visibility for front-end.', 'italystrap'),
                    'id'            => 'widget_visibility',
                    'type'          => 'checkbox',
                    'class'         => 'widget_visibility medium',
                    'default'       => '',
                    // 'validate'   => 'ctype_alpha',
                    'sanitize'      => 'sanitize_text_field',
                ],
            ],
            [
                'id'        => 'widget_attributes',
                'title'     => __('HTML attributes for widget', 'italystrap'),
                'args'      => [
                    'label'         => __('Activate two new input HTML attributes for every widget', 'italystrap'),
                    'desc'          => __('This will add two new input in every widget that allow for custom <code>id</code> and <code>class</code> attributes in the widget container.', 'italystrap'),
                    'id'            => 'widget_attributes',
                    'type'          => 'checkbox',
                    'class'         => 'widget_attributes medium',
                    'default'       => '',
                    // 'validate'   => 'ctype_alpha',
                    'sanitize'      => 'sanitize_text_field',
                ],
            ],
            [
                'id'        => 'render_html_in_widget_title',
                'title'     => __('HTML in Widget Title', 'italystrap'),
                'args'      => [
                    'label'         => __('Render HTML in Widget Title', 'italystrap'),
                    'desc'          => __('Activate this if you want to add an HTML tag to Widget title: replace the opening and closing tags with <code>{{</code> and <code>}}</code>. E.g.: <code>&lt;strong&gt;Widget Title&lt;/strong&gt;</code> <strong>becomes</strong> <code>{{strong}}Widget Title{{/strong}}</code>', 'italystrap'),
                    'id'            => 'render_html_in_widget_title',
                    'type'          => 'checkbox',
                    'class'         => 'render_html_in_widget_title medium',
                    'default'       => '',
                    // 'validate'   => 'ctype_alpha',
                    'sanitize'      => 'sanitize_text_field',
                ],
            ],
            [
                'id'        => 'remove_widget_title',
                'title'     => __('Remove widget title', 'italystrap'),
                'args'      => [
                    'label'         => __('Remove widget title conditionally', 'italystrap'),
                    'desc'          => __('Add <code>!!</code> (2 exclamation marks) at the beginning of the widget title to hide it. Example: <code>!!My widget title.</code>', 'italystrap'),
                    'id'            => 'remove_widget_title',
                    'type'          => 'checkbox',
                    'class'         => 'remove_widget_title easy',
                    'default'       => '',
                    // 'validate'   => 'ctype_alpha',
                    'sanitize'      => 'sanitize_text_field',
                ],
            ],
            [
                'id'        => 'custom_tag_cloud',
                'title'     => __('Add some style to the built-in Tag Cloud', 'italystrap'),
                'args'      => [
                    'label'         => __('Tag Cloud for ItalyStrap', 'italystrap'),
                    'desc'          => __('', 'italystrap'),
                    'id'            => 'custom_tag_cloud',
                    'type'          => 'checkbox',
                    'class'         => 'custom_tag_cloud easy',
                    'default'       => '',
                    // 'validate'   => 'ctype_alpha',
                    'sanitize'      => 'sanitize_text_field',
                ],
                'show_on'               => Core\is_italystrap_active(),
            ],
            [
                'id'        => 'widget_posts',
                'title'     => __('Posts Widget', 'italystrap'),
                'args'      => [
                    'label'         => __('Widget for custom loop of posts , pages and custom post types', 'italystrap'),
                    'desc'          => __('This widget allow you to create a custom loop of posts/page/CPT with a lot of options like "Recent Posts" or "Posts more comented" or "Related posts" ecc and place it in your sidebars. (This plugin does not provide any style, you have to add it in the style.css of your theme)', 'italystrap'),
                    'id'            => 'widget_posts',
                    'type'          => 'checkbox',
                    'class'         => 'widget_posts hard',
                    'default'       => '',
                    // 'validate'   => 'ctype_alpha',
                    'sanitize'      => 'sanitize_text_field',
                ],
            ],
            // array(
            //  'id'        => 'widget_grouped_posts',
            //  'title'     => __( 'Grouped Posts Widget', 'italystrap' ),
            //  'callback'  => 'get_field_type',
//          //  'page'      => 'italystrap_options_group',
            //  'section'   => 'widget',
            //  'args'      => array(
            //          'label'         => __( 'Posts Grouped by Taxonomies (cats, tags and custom tax)', 'italystrap' ) . $beta,
            //          'desc'          => __( 'This widget allow you to create a lists of custom loop of any posts type regrouped by taxonomies with a lot of options. (This plugin does not provide any style, you have to add it in the style.css of your theme)', 'italystrap' ),
            //          'id'            => 'widget_grouped_posts',
            //          'type'          => 'checkbox',
            //          'class'         => 'widget_grouped_posts hard',
            //          'default'       => '',
            //          // 'validate'   => 'ctype_alpha',
            //          'sanitize'      => 'sanitize_text_field',
            //  ),
            //  'show_on'               => \ItalyStrap\Core\is_dev(),
            // ),
            [
                'id'        => 'media_carousel_widget',
                'title'     => __('Carousel Widget', 'italystrap'),
                'args'      => [
                    'label'         => __('Widget for Media Carousel', 'italystrap'),
                    'desc'          => __('This will activate a Bootstrap media Carousel with a ton of options, make shure you have a Twitter Bootstrap CSS in your site.', 'italystrap'),
                    'id'            => 'media_carousel_widget',
                    'type'          => 'checkbox',
                    'class'         => 'media_carousel_widget medium',
                    'default'       => '',
                    // 'validate'   => 'ctype_alpha',
                    'sanitize'      => 'sanitize_text_field',
                ],
            ],
            [
                'id'        => 'widget_vcard',
                'title'     => __('vCard Widget', 'italystrap'),
                'args'      => [
                    'label'         => __('vCard Local Business', 'italystrap'),
                    'desc'          => __('Add a vCard Local Business with Schema.org markup to your theme widgetized area. (This plugin does not provide any style, you have to add it in the style.css of your theme).', 'italystrap'),
                    'id'            => 'widget_vcard',
                    'type'          => 'checkbox',
                    'class'         => 'widget_vcard medium',
                    'default'       => '',
                    // 'validate'   => 'ctype_alpha',
                    'sanitize'      => 'sanitize_text_field',
                ],
            ],
            [
                'id'        => 'widget_image',
                'title'     => __('Image Widget', 'italystrap'),
                'args'      => [
                    'label'         => __('Image Widget', 'italystrap') . $beta,
                    'desc'          => __('Activate image widget and displays an image from media with an array of options. (This plugin does not provide any style, you have to add it in the style.css of your theme).', 'italystrap'),
                    'id'            => 'widget_image',
                    'type'          => 'checkbox',
                    'class'         => 'widget_image medium',
                    'default'       => '',
                    // 'validate'   => 'ctype_alpha',
                    'sanitize'      => 'sanitize_text_field',
                ],
                'show_on'               => Core\is_beta(),
            ],
            // array(
            //  'id'        => 'widget_breadcrumbs',
            //  'title'     => __( 'Breadcrumbs Widget', 'italystrap' ),
            //  'callback'  => 'get_field_type',
//          //  'page'      => 'italystrap_options_group',
            //  'section'   => 'widget',
            //  'args'      => array(
            //          'label'         => __( 'Breadcrumbs Widget with Schema.org markup', 'italystrap' ) . $beta,
            //          'desc'          => __( 'Activate Breadcrumbs widget with Schema.org markup. (This plugin does not provide any style, you have to add it in the style.css of your theme)', 'italystrap' ),
            //          'id'            => 'widget_breadcrumbs',
            //          'type'          => 'checkbox',
            //          'class'         => 'widget_breadcrumbs hard',
            //          'default'       => '',
            //          // 'validate'   => 'ctype_alpha',
            //          'sanitize'      => 'sanitize_text_field',
            //  ),
            //  'show_on'               => \ItalyStrap\Core\is_dev(),
            // ),
            // array(
            //  'id'        => 'widget_facebook_page',
            //  'title'     => __( 'Facebook Page Widget', 'italystrap' ),
            //  'callback'  => 'get_field_type',
//          //  'page'      => 'italystrap_options_group',
            //  'section'   => 'widget',
            //  'args'      => array(
            //          'label'         => __( 'Facebook Page Widget', 'italystrap' ) . $beta,
            //          'desc'          => __( 'Embed a Facebook Page on your site with a widget.', 'italystrap' ),
            //          'id'            => 'widget_facebook_page',
            //          'type'          => 'checkbox',
            //          'class'         => 'widget_facebook_page hard',
            //          'default'       => '',
            //          // 'validate'   => 'ctype_alpha',
            //          'sanitize'      => 'sanitize_text_field',
            //  ),
            //  'show_on'               => \ItalyStrap\Core\is_dev(),
            // ),
            // array(
            //  'id'        => 'widget_editor',
            //  'title'     => __( 'Editor Widget', 'italystrap' ),
            //  'callback'  => 'get_field_type',
//          //  'page'      => 'italystrap_options_group',
            //  'section'   => 'widget',
            //  'args'      => array(
            //          'label'         => __( 'TinyMCE Editor Widget', 'italystrap' ) . $beta,
            //          'desc'          => __( 'Adds the TinyMCE visual editor widget.', 'italystrap' ),
            //          'id'            => 'widget_editor',
            //          'type'          => 'checkbox',
            //          'class'         => 'widget_editor hard',
            //          'default'       => '',
            //          // 'validate'   => 'ctype_alpha',
            //          'sanitize'      => 'sanitize_text_field',
            //  ),
            //  'show_on'               => \ItalyStrap\Core\is_dev(),
            // ),
            [
                'id'        => 'widget_nav_menu',
                'title'     => __('Nav Menu Widget', 'italystrap'),
                'args'      => [
                    'label'         => __('Nav Menu Widget', 'italystrap') . $beta,
                    'desc'          => __('Add an advanced custom menu to your sidebar. Available only for ItalyStrap theme framework.', 'italystrap'),
                    'id'            => 'widget_nav_menu',
                    'type'          => 'checkbox',
                    'class'         => 'widget_nav_menu hard',
                    'default'       => '',
                    // 'validate'   => 'ctype_alpha',
                    'sanitize'      => 'sanitize_text_field',
                ],
                'show_on'               => Core\is_beta() && Core\is_italystrap_active(),
            ],
            [
                'id'        => 'widget_monster',
                'title'     => __('Monster Widget', 'italystrap'),
                'args'      => [
                    'label'         => __('Monster Widget by ItalyStrap {{Only for debug}}', 'italystrap'),
                    'desc'          => __('Test multiple widgets by ItalyStrap at the same time.', 'italystrap'),
                    'id'            => 'widget_monster',
                    'type'          => 'checkbox',
                    'class'         => 'widget_monster hard',
                    'default'       => '',
                    // 'validate'   => 'ctype_alpha',
                    'sanitize'      => 'sanitize_text_field',
                ],
                'show_on'               => Core\is_debug(),
            ],
            // array(
            //  'id'        => 'vcardwidget',
            //  'title'     => __( 'vCard Widget (DEPRECATED)', 'italystrap' ),
            //  'callback'  => 'get_field_type',
//          //  'page'      => 'italystrap_options_group',
            //  'section'   => 'widget',
            //  'args'      => array(
            //          'label'         => __( 'ItalyStrap vCard Widget for Local Business (DEPRECATED)', 'italystrap' ),
            //          'desc'          => __( 'Activate a widget for vCard Local Business with schema.org markup (DEPRECATED)', 'italystrap' ),
            //          'id'            => 'vcardwidget',
            //          'type'          => 'checkbox',
            //          'class'         => 'vcardwidget',
            //          'default'       => '',
            //          // 'validate'   => 'ctype_alpha',
            //          'sanitize'      => 'sanitize_text_field',
            //  ),
            // ),
            // array( // DEPRECATED
            //  'id'        => 'post_widget',
            //  'title'     => __( 'Posts Widget (DEPRECATED)', 'italystrap' ),
            //  'callback'  => 'get_field_type',
//          //  'page'      => 'italystrap_options_group',
            //  'section'   => 'widget',
            //  'args'      => array(
            //          'label'         => __( 'Posts Widget for Custom Loop (DEPRECATED)', 'italystrap' ),
            //          'desc'          => __( 'Activate posts widget and displays list of posts with an array of options', 'italystrap' ),
            //          'id'            => 'post_widget',
            //          'type'          => 'checkbox',
            //          'class'         => 'post_widget',
            //          'default'       => '',
            //          // 'validate'   => 'ctype_alpha',
            //          'sanitize'      => 'sanitize_text_field',
            //  ),
            // ),
        ],
    ],
    /**
     * This is the Lazy Load configuration
     */
    'shortcode' => [
        'tab_title'         => __('Shortcodes', 'italystrap'),
        'id'                => 'shortcode',
        'title'             => __('Options page for shortcodes', 'italystrap'),
        'desc'              => __('Select the shortcodes you want to use.', 'italystrap'),
        'settings_fields'   => [
            [
                'id'        => 'do_shortcode_widget_text',
                'title'     => __('Do ShortCode in Widget Text', 'italystrap'),
                'args'      => [
                    'label'         => __('Do ShortCode in Widget Text', 'italystrap'),
                    'desc'          => __('This get you the possibility to insert any shortcode into a widget text.', 'italystrap'),
                    'id'            => 'do_shortcode_widget_text',
                    'type'          => 'checkbox',
                    'class'         => 'do_shortcode_widget_text easy',
                    'default'       => '',
                    // 'validate'   => 'ctype_alpha',
                    'sanitize'      => 'sanitize_text_field',
                ],
            ],
            // array(
            //  'id'        => 'shortcode_widget',
            //  'title'     => __( 'Widget to ShortCode', 'italystrap' ),
            //  'callback'  => 'get_field_type',
//          //  'page'      => 'italystrap_options_group',
            //  'section'   => 'shortcode',
            //  'args'      => array(
            //          'label'         => __( 'Render Widget to ShortCode', 'italystrap' ) . $beta,
            //          'desc'          => __( 'You can add any widgets in a new shortcode <code>[widget id=""]</code> to show it in your content. (ALPHA VERSION)', 'italystrap' ),
            //          'id'            => 'shortcode_widget',
            //          'type'          => 'checkbox',
            //          'class'         => 'shortcode_widget hard',
            //          // 'default'        => 1,
            //          // 'validate'   => 'ctype_alpha',
            //          'sanitize'      => 'sanitize_text_field',
            //  ),
            //  'show_on'               => Core\is_beta(),
            // ),
            [
                'id'        => 'media_carousel_shortcode',
                'title'     => __('Carousel Shortcode', 'italystrap'),
                'args'      => [
                    'label'         => __('Shortcode for Media Carousel', 'italystrap'),
                    'desc'          => __('This will activate a Bootstrap media Carousel inside built-in WordPress gallery shortcode with a ton of options, make shure you have a Twitter Bootstrap CSS in your site.', 'italystrap'),
                    'id'            => 'media_carousel_shortcode',
                    'type'          => 'checkbox',
                    'class'         => 'media_carousel_shortcode medium',
                    'default'       => '',
                    // 'validate'   => 'ctype_alpha',
                    'sanitize'      => 'sanitize_text_field',
                ],
            ],
            [
                'id'        => 'shortcode_posts',
                'title'     => __('Posts Shortcode', 'italystrap'),
                'args'      => [
                    'label'         => __('Shortcode for custom loop of posts , pages and custom post types', 'italystrap') . $beta,
                    'desc'          => __('This shortcode allow you to create a custom loop of posts/page/CPT with a lot of options like "Recent Posts" or "Posts more comented" or "Related posts" ecc and place it in your sidebars. (This plugin does not provide any style, you have to add it in the style.css of your theme).', 'italystrap'),
                    'id'            => 'shortcode_posts',
                    'type'          => 'checkbox',
                    'class'         => 'shortcode_posts medium',
                    // 'default'        => '0',
                    // 'validate'   => 'ctype_alpha',
                    'sanitize'      => 'sanitize_text_field',
                ],
                'show_on'               => Core\is_beta(),
            ],
            [
                'id'        => 'shortcode_post_title',
                'title'     => __('Post Title Shortcode', 'italystrap'),
                'args'      => [
                    'label'         => __('Shortcode for display post, page or CPT title', 'italystrap'),
                    'desc'          => __('This shortcode allow you to display the title of the post you want to display, If you want to display the title in a different page you have to insert the ID of the post you want to display.', 'italystrap'),
                    'id'            => 'shortcode_post_title',
                    'type'          => 'checkbox',
                    'class'         => 'shortcode_post_title medium',
                    // 'validate'   => 'ctype_alpha',
                    'sanitize'      => 'sanitize_text_field',
                ],
                // 'show_on'                => Core\is_beta(),
            ],
            // array(
            //  'id'        => 'shortcode_button',
            //  'title'     => __( 'Post Button Shortcode', 'italystrap' ),
            //  'callback'  => 'get_field_type',
//          //  'page'      => 'italystrap_options_group',
            //  'section'   => 'shortcode',
            //  'args'      => array(
            //          'label'         => __( 'Shortcode for display post, page or CPT title', 'italystrap' ),
            //          'desc'          => __( 'This shortcode allow you to display the title of the post you want to display, If you want to display the title in a different page you have to insert the ID of the post you want to display.', 'italystrap' ),
            //          'id'            => 'shortcode_button',
            //          'type'          => 'checkbox',
            //          'class'         => 'shortcode_button medium',
            //          // 'default'        => '0',
            //          // 'validate'   => 'ctype_alpha',
            //          'sanitize'      => 'sanitize_text_field',
            //  ),
            //  'show_on'               => \ItalyStrap\Core\is_dev(),
            // ),
            // array(
            //  'id'        => 'shortcode_row',
            //  'title'     => __( 'Row Shortcode', 'italystrap' ),
            //  'callback'  => 'get_field_type',
//          //  'page'      => 'italystrap_options_group',
            //  'section'   => 'shortcode',
            //  'args'      => array(
            //          'label'         => __( 'Shortcode for a row html container', 'italystrap' ) . $beta,
            //          'desc'          => __( 'This shortcode is meant to use with the column shortcode, this is an HTML container, the shortcode renders a div elements and you can add CSS ID, class and style in the shortcode parameters. If you use Twitter Bootstrap you can use <code>row</code>. By default this shortcode doesn\' add any css, use yours theme style.css.', 'italystrap' ),
            //          'id'            => 'shortcode_row',
            //          'type'          => 'checkbox',
            //          'class'         => 'shortcode_row medium',
            //          'default'       => '0',
            //          // 'validate'   => 'ctype_alpha',
            //          'sanitize'      => 'sanitize_text_field',
            //  ),
            //  'show_on'               => Core\is_beta(),
            // ),
            // array(
            //  'id'        => 'shortcode_column',
            //  'title'     => __( 'Column Shortcode', 'italystrap' ),
            //  'callback'  => 'get_field_type',
//          //  'page'      => 'italystrap_options_group',
            //  'section'   => 'shortcode',
            //  'args'      => array(
            //          'label'         => __( 'Shortcode for html columns', 'italystrap' ) . $beta,
            //          'desc'          => __( 'With this shortcode you can insert as many column as you want, the limits it\'s what you have in your style.css. If you use Twitter Bootstrap you can use <code>col-lg-*</code> <code>col-md-*</code> <code>col-sm-*</code> <code>col-xs-*</code>. By default this shortcode doesn\' add any css, use yours theme style.css.', 'italystrap' ),
            //          'id'            => 'shortcode_column',
            //          'type'          => 'checkbox',
            //          'class'         => 'shortcode_column medium',
            //          'default'       => '0',
            //          // 'validate'   => 'ctype_alpha',
            //          'sanitize'      => 'sanitize_text_field',
            //  ),
            //  'show_on'               => Core\is_beta(),
            // ),
        ],
    ],
    /**
     * This is the CSS configuration
     */
    'style' => [
        'tab_title'         => __('Style', 'italystrap'),
        'id'                => 'style',
        'title'             => __('Options page for style purpose', 'italystrap'),
        'desc'              => __('This is the tab for changing the style of your site. Code entered here will be included in every page of the front-end of your site.', 'italystrap'),
        'settings_fields'   => [
            [
                'id'        => 'activate_custom_css',
                'title'     => __('Activate Custom CSS', 'italystrap'),
                'args'      => [
                    'label'         => __('Activate Custom CSS', 'italystrap'),
                    'desc'          => __('This will add new fields in the wp editor for adding custom CSS, ID and class attribute to post/page and also it let you use the new functionality below.', 'italystrap'),
                    'id'            => 'activate_custom_css',
                    'type'          => 'checkbox',
                    'class'         => 'activate_custom_css medium',
                    'default'       => '',
                    // 'validate'   => 'ctype_alpha',
                    'sanitize'      => 'sanitize_text_field',
                    'option_type'   => 'theme_mod',
                ],
            ],
            [
                'id'            => 'custom_css',
                'title'         => __('Custom CSS', 'italystrap'),
                'args'          => [
                    'desc'          => __('Enter your custom CSS, this styles will be included verbatim in <style> tags in the <code>&lt;head&gt;</code> element of your html. The code will appear before styles that were registered individually and after your styles enqueued with the WordPress API.', 'italystrap'),
                    'id'            => 'custom_css',
                    'type'          => 'textarea',
                    'class'         => 'custom_css medium',
                    'rows'          => 20,
                    'cols'          => 100,
                    'placeholder'   => '.my_css{color:#fff;}',
                    'default'       => '',
                    // 'validate'       => 'ctype_alpha',
                    // 'sanitize'       => 'sanitize_text_field|strip_tags', // Default: strip_tags
                    'option_type'   => 'theme_mod',
                ],
            ],
            [
                'id'            => 'body_class',
                'title'         => __('Body Class', 'italystrap'),
                'args'          => [
                    'desc'          => __('This will add a CSS class to <code>body_class</code> filter in every page.', 'italystrap'),
                    'id'            => 'body_class',
                    'type'          => 'text',
                    'class'         => 'body_class medium',
                    'placeholder'   => '',
                    'default'       => '',
                    'validate'      => 'ctype_alpha',
                    'sanitize'      => 'sanitize_text_field',
                    'option_type'   => 'theme_mod',
                ],
            ],
            [
                'id'            => 'post_class',
                'title'         => __('Post Class', 'italystrap'),
                'args'          => [
                    'desc'          => __('This will add a CSS class to <code>post_class</code> filter in every page.', 'italystrap'),
                    'id'            => 'post_class',
                    'type'          => 'text',
                    'class'         => 'post_class medium',
                    'placeholder'   => '',
                    'default'       => '',
                    'validate'      => 'ctype_alpha',
                    'sanitize'      => 'sanitize_text_field',
                    'option_type'   => 'theme_mod',
                ],
            ],
        ],
    ],
    /**
     * This is the Script configuration
     */
    // 'script' => array(
    //  'tab_title'         => __( 'Script', 'italystrap' ),
    //  'id'                => 'script',
    //  'title'             => __( 'ItalyStrap options page for script purpose', 'italystrap' ),
    //  'callback'          => 'render_section_cb',
    //  'desc'              => __( 'This is the tab for adding custom script of your site. Code entered here will be included in every page of the front-end of your site in the footer of the page.', 'italystrap' ),
//  //  'page'              => 'italystrap_options_group',
    //  'settings_fields'   => array(
    //      array(
    //          'id'        => 'activate_custom_script',
    //          'title'     => __( 'Activate Custom Script', 'italystrap' ),
    //          'callback'  => 'get_field_type',
//  //          'page'      => 'italystrap_options_group',
    //          'section'   => 'script',
    //          'args'      => array(
    //                  'label'         => __( 'Custom Script', 'italystrap' ),
    //                  'desc'          => __( 'This will add new fields in the wp editor for adding custom Script to post/page and also let you use the new functionality below.', 'italystrap' ),
    //                  'id'            => 'activate_custom_script',
    //                  'type'          => 'checkbox',
    //                  'class'         => 'activate_custom_css medium',
    //                  'default'       => '',
    //                  // 'validate'   => 'ctype_alpha',
    //                  'sanitize'      => 'sanitize_text_field',
    //                  'option_type'   => 'theme_mod',
    //          ),
    //      ),
    //      array(
    //          'id'            => 'custom_script',
    //          'title'         => __( 'Custom Script', 'italystrap' ),
    //          'callback'      => 'get_field_type',
    //          'page'          => 'italystrap_options_group',
    //          'section'       => 'script',
    //          'args'          => array(
    //                  '_name'         => 'italystrap_settings[custom_script]',
    //                  '_id'           => 'italystrap_settings[custom_script]',
    //                  'label'         => __( 'Custom Script', 'italystrap' ),
    //                  'desc'          => __( 'Enter your custom Script, this scripts will be included verbatim before the <code>&lt;/body&gt;</code> element of your html.', 'italystrap' ),
    //                  'id'            => 'custom_script',
    //                  'type'          => 'textarea',
    //                  'class'         => 'custom_script medium',
    //                  'rows'          => 20,
    //                  'cols'          => 100,
    //                  'placeholder'   => '',
    //                  'default'       => '',
    //                  // 'validate'       => 'ctype_alpha',
    //                  'sanitize'      => 'sanitize_text_field',
    //                  'option_type'   => 'theme_mod',
    //          ),
    //      ),
    //  ),
    // ),
    /**
     * This is the Script configuration
     */
    'analytics' => [
        'tab_title'         => Core\is_beta() ? __('GA + GTM', 'italystrap') : __('GA', 'italystrap'),
        'id'                => 'analytics',
        'title'             => __('Options page for Google Analytics', 'italystrap'),
        'desc'              => __('Here you can configure google analytics settings and activate the GA tracking code in your site.', 'italystrap'),
        'settings_fields'   => [
            [
                'id'        => 'activate_analytics',
                'title'     => __('Activate Google Analytics', 'italystrap'),
                'args'      => [
                    'label'         => __('Activate Google analitycs script', 'italystrap'),
                    'desc'          => __('This will add the Google analytics script in every page of your site before the <code>&lt;/body&gt;</code> tag. The snippet will be appended to <code>wp_footer</code> hook.', 'italystrap'),
                    'id'            => 'activate_analytics',
                    'type'          => 'checkbox',
                    'class'         => 'activate_analytics easy',
                    'default'       => '',
                    // 'validate'   => 'ctype_alpha',
                    'sanitize'      => 'sanitize_text_field',
                ],
            ],
            [
                'id'        => 'google_tag_manager_id',
                'title'     => __('Google Tag Manager ID', 'italystrap'),
                'args'      => [
                    'desc'          => __('Available only for ItalyStrap theme framework. Insert your google tag manager ID', 'italystrap') . $beta,
                    'id'            => 'google_tag_manager_id',
                    'type'          => 'text',
                    'class'         => 'google_tag_manager_id easy',
                    'default'       => '',
                    // 'validate'   => 'ctype_alpha',
                    'sanitize'      => 'sanitize_text_field',
                ],
                'show_on'               => Core\is_beta() && Core\is_italystrap_active(),
            ],
            [
                'id'        => 'google_analytics_id',
                'title'     => __('Google Analytics ID', 'italystrap'),
                'args'      => [
                    'desc'          => __('Insert your google analytics ID', 'italystrap'),
                    'id'            => 'google_analytics_id',
                    'type'          => 'text',
                    'class'         => 'google_analytics_id easy',
                    'default'       => '',
                    // 'validate'   => 'ctype_alpha',
                    'sanitize'      => 'sanitize_text_field',
                ],
            ],
            [
                'id'        => 'google_analytics_anonymizeIp',
                'title'     => __('Anonymize Google Analytics IP', 'italystrap'),
                'args'      => [
                    'label'         => __('Anonymize IP', 'italystrap'),
                    'desc'          => __('Do you want to anonymize Google Analytics IP?', 'italystrap'),
                    'id'            => 'google_analytics_anonymizeIp',
                    'type'          => 'checkbox',
                    'class'         => 'google_analytics_anonymizeIp easy',
                    'default'       => '',
                    // 'validate'   => 'ctype_alpha',
                    'sanitize'      => 'sanitize_text_field',
                ],
            ],
            [
                'id'        => 'google_analytics_position',
                'title'     => __('Google Analytics position', 'italystrap'),
                'args'      => [
                    'desc'          => __('Select the position for Google Analytics. Default: <code>wp_footer</code>. Note: If you verify your site in search console you have to set <code>wp_head</code>.', 'italystrap'),
                    'id'            => 'google_analytics_position',
                    'type'          => 'select',
                    'options'       => [
                        'wp_footer' => __('Before the &lt;/body&gt; closed', 'italystrap'),
                        'wp_head'   => __('Before the &lt;/head&gt; closed', 'italystrap'),
                    ],
                    'class'         => 'google_analytics_position easy',
                    'default'       => 'wp_footer',
                    // 'validate'   => 'ctype_alpha',
                    'sanitize'      => 'sanitize_text_field',
                ],
            ],
        ],
    ],
    /**
     * Settings for the content area
     */
    'content'   => [
        'tab_title'         => __('Content', 'italystrap'),
        'id'                => 'content',
        'title'             => __('Options page for the content area', 'italystrap'),
        'desc'              => __('Here you can configure the content area in your site.', 'italystrap'),
        'settings_fields'   => [
            [
                'id'        => 'activate_excerpt_more_mods',
                'title'     => __('Activate excerpt more mods', 'italystrap'),
                'args'      => [
                    'label'         => __('Activate excerpt more mods', 'italystrap'),
                    'desc'          => __('Activate the excerpt more mods for this theme. This functionality will be saved to the <code>theme_mods();</code>. It also works for the Widget Post if you select "Use global readmore" in the widget itself.', 'italystrap'),
                    'id'            => 'activate_excerpt_more_mods',
                    'type'          => 'checkbox',
                    'class'         => 'activate_excerpt_more_mods easy',
                    'default'       => '',
                    // 'validate'       => 'ctype_alpha',
                    'sanitize'      => 'sanitize_text_field',
                    'option_type'   => 'theme_mod',
                ],
            ],
            [
                'id'        => 'read_more_link_text',
                'title'     => __('Read more link text', 'italystrap'),
                'args'      => [
                    'desc'          => __('Customize the read more link pattern. Default: <code>&hellip;Read more</code>', 'italystrap'),
                    'id'            => 'read_more_link_text',
                    'type'          => 'text',
                    'class'         => 'read_more_link_text easy',
                    'default'       => __('&hellip;Read more', 'italystrap'),
                    'validate'      => 'ctype_alpha',
                    'sanitize'      => 'sanitize_text_field',
                    'translate'     => true,
                    'option_type'   => 'theme_mod',
                ],
            ],
            [
                'id'        => 'read_more_class',
                'title'     => __('Read more CSS class', 'italystrap'),
                'args'      => [
                    'desc'          => __('Customize the style of the read more link with your custom CSS class. Default: <code>read-more</code>. Example: <code>read-more btn btn-primary btn-lg</code>.', 'italystrap'),
                    'id'            => 'read_more_class',
                    'type'          => 'text',
                    'class'         => 'read_more_class easy',
                    'default'       => 'read-more',
                    'validate'      => 'ctype_alpha',
                    'sanitize'      => 'sanitize_text_field',
                    'option_type'   => 'theme_mod',
                ],
            ],
            [
                'id'        => 'excerpt_length',
                'title'     => __('Auto-generated Excerpt length', 'italystrap'),
                'args'      => [
                    'desc'          => __('The default length for auto-generated excerpts is 55 words. It works only if the excerpt field is empty.', 'italystrap'),
                    'id'            => 'excerpt_length',
                    'type'          => 'number',
                    'class'         => 'excerpt_length easy',
                    'default'       => '55',
                    'validate'      => 'is_numeric|is_int',
                    'sanitize'      => 'sanitize_text_field',
                    'option_type'   => 'theme_mod',
                ],
            ],
            [
                'id'        => 'end_with_punctuation',
                'title'     => __('Excerpt ends with punctuation', 'italystrap'),
                'args'      => [
                    'label'         => __('Auto-generated Excerpt ends with punctuation', 'italystrap'),
                    'desc'          => __('Auto-generated Excerpt ends with punctuation (by default . or ? or !). It works only if the excerpt field is empty.', 'italystrap'),
                    'id'            => 'end_with_punctuation',
                    'type'          => 'checkbox',
                    'class'         => 'end_with_punctuation easy',
                    'default'       => '',
                    // 'validate'       => 'is_numeric|is_int',
                    'sanitize'      => 'sanitize_text_field',
                    'option_type'   => 'theme_mod',
                ],
            ],
            [
                'id'        => 'read_more_position',
                'title'     => __('Read more position', 'italystrap'),
                'args'      => [
                    'desc'          => __('Select the position to display read more link. With <code>Append</code> the read more link will be appended just after the text inside the HTML paragraph, with <code>After</code> it will be added after and outside the last HTML paragraph on a new line, this is useful if you add a button style to the "Read more".', 'italystrap'),
                    'id'            => 'read_more_position',
                    'type'          => 'select',
                    'options'       => [
                        'append'    => __('Append to the excerpt', 'italystrap'),
                        'after'     => __('After the excerpt', 'italystrap'),
                    ],
                    'class'         => 'read_more_position easy',
                    'default'       => 'append',
                    // 'validate'   => 'ctype_alpha',
                    'sanitize'      => 'sanitize_text_field',
                ],
            ],
        ],
    ],
    /**
     * This is the Lazy Load configuration
     */
    'media' => [
        'tab_title'         => __('Media', 'italystrap'),
        'id'                => 'media',
        'title'             => __('Settings page for media add-on functionality', 'italystrap'),
        'desc'              => __('In this section you can customize the way your WordPress handles media.', 'italystrap'),
        'settings_fields'   => [
            [
                'id'        => 'jpeg_quality',
                'title'     => __('Jpeg quality', 'italystrap'),
                'args'      => [
                    'desc'          => __('Select the jpeg quality for images. Best value: 100, worse value: 75, default: 82', 'italystrap'),
                    'id'            => 'jpeg_quality',
                    'type'          => 'number',
                    'class'         => 'jpeg_quality easy',
                    'default'       => 82,
                    'validate'      => 'is_numeric|is_int',
                    'sanitize'      => 'sanitize_text_field',
                    'option_type'   => 'theme_mod',
                ],
            ],
            [
                'id'        => 'lazyload',
                'title'     => __('Lazy Loading for images', 'italystrap'),
                'args'      => [
                    'label'         => __('Lazy Loading for images', 'italystrap'),
                    'desc'          => __('Activate Lazy Loading for images', 'italystrap'),
                    'id'            => 'lazyload',
                    'type'          => 'checkbox',
                    'class'         => 'lazyload easy',
                    'default'       => '',
                    // 'validate'   => 'ctype_alpha',
                    'sanitize'      => 'sanitize_text_field',
                    'option_type'   => 'theme_mod',
                ],
            ],
            [
                'id'            => 'lazyload-custom-placeholder',
                'title'         => __('Custom Placeholder', 'italystrap'),
                'args'          => [
                    'desc'          => sprintf(
                        __('Insert here your custom placeholder for image lazyloading from your media file, this is the src attribute of the img tag.
						%1$sExample: %2$s %1$sDefault (transparent): %3$s %1$sFor more info: %4$s', 'italystrap'),
                        '<br>',
                        ' <code>' . $wp_upload_dir['url'] . '/my-placeholder.gif</code>',
                        '<code>data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7</code>',
                        esc_url('http://clubmate.fi/base64-encoded-1px-gifs-black-gray-and-transparent/')
                    ),
                    'id'            => 'lazyload-custom-placeholder',
                    'type'          => 'text',
                    'class'         => 'lazyload-custom-placeholder medium',
                    'placeholder'   => '',
                    'default'       => 'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7',
                    // 'validate'       => 'esc_url',
                    'sanitize'      => 'sanitize_text_field',
                    'option_type'   => 'theme_mod',
                ],
            ],
            // array(
            //  'id'        => 'image_size',
            //  'title'     => __( 'Image Size', 'italystrap' ),
            //  'callback'  => 'get_field_type',
//          //  'page'      => 'italystrap_options_group',
            //  'section'   => 'media',
            //  'args'      => array(
            //      'label'         => __( 'Add Image Size', 'italystrap' ) . $beta,
            //      'desc'          => __( 'Add Image Size for this theme', 'italystrap' ),
            //      'id'            => 'image_size',
            //      'type'          => 'group',
            //      'group_field'   => array(
            //          array(
            //              'label'         => __( 'Image Size Name', 'italystrap' ),
            //              'desc'          => '',
            //              'id'            => 'image_size_name',
            //              'type'          => 'text',
            //              'default'       => '',
            //              'validate'      => 'ctype_alpha',
            //              'sanitize'      => 'sanitize_text_field',
            //          ),
            //          array(
            //              'label'         => __( 'Image Size Width', 'italystrap' ),
            //              'desc'          => '',
            //              'id'            => 'image_size_width',
            //              'type'          => 'number',
            //              'default'       => '',
            //              'validate'      => 'is_numeric|is_int',
            //              'sanitize'      => 'sanitize_text_field',
            //          ),
            //          array(
            //              'label'         => __( 'Image Size Height', 'italystrap' ),
            //              'desc'          => '',
            //              'id'            => 'image_size_height',
            //              'type'          => 'number',
            //              'default'       => '',
            //              'validate'      => 'is_numeric|is_int',
            //              'sanitize'      => 'sanitize_text_field',
            //          ),
            //          array(
            //              'label'         => __( 'Image Size Crop', 'italystrap' ),
            //              'desc'          => '',
            //              'id'            => 'image_size_crop',
            //              'type'          => 'checkbox',
            //              'default'       => '',
            //              // 'validate'       => 'is_numeric|is_int',
            //              'sanitize'      => 'sanitize_text_field',
            //          ),
            //      ),
            //      'class'         => 'image_size easy',
            //      // 'default'        => 82,
            //      // 'validate'       => 'is_numeric|is_int',
            //      // 'sanitize'       => 'sanitize_text_field',
            //      'option_type'   => 'theme_mod',
            //  ),
            //  'show_on'               => Core\is_beta(),
            // ),
            [
                'id'        => 'lazyload_additional_event_name',
                'title'     => __('Additional event name to lazy load', 'italystrap'),
                'args'      =>  [
//                  'label'         => __( 'Additional hooks to lazy load the content', 'italystrap' ),
                    'desc'          => __('Insert additional event name (hooks) in the textarea below
		Put one event per line, if you need to specify a priority separate it with <code>|</code>, the dafult is 10.
		Default arguments accepted are 3', 'italystrap'),
                    'id'            => 'lazyload_additional_event_name',
                    'type'          => 'textarea',
                    'class'         => 'easy',
                    'placeholder'   => 'some-event-name|priority',
                    'sanitize'      => 'sanitize_textarea_field',
                    'option_type'   => 'theme_mod',
                    'show_on'       => Core\is_beta(),
                ],
                'show_on'               => Core\is_beta(),
            ],
            [
                'id'        => 'lazyload_video',
                'title'     => __('Lazy Loading for embedded video', 'italystrap'),
                'args'      => [
                    'label'         => __('Lazy Loading for embedded video', 'italystrap') . $beta,
                    'desc'          => __('Activate Lazy Loading for embedded video. This only works for youtube video. The with of the container will be the max with of <code>content_width</code> set in your theme. You can use the <code>lazyload-video-wrap</code> CSS class for adding your own style.', 'italystrap'),
                    'id'            => 'lazyload_video',
                    'type'          => 'checkbox',
                    'class'         => 'lazyload_video easy',
                    'default'       => '',
                    // 'validate'   => 'ctype_alpha',
                    'sanitize'      => 'sanitize_text_field',
                    'option_type'   => 'theme_mod',
                ],
                'show_on'               => Core\is_beta(),
            ],
        ],
    ],
];
