<?php
/**
 * Array definition for carousel default options
 *
 * @package ItalyStrap
 */

if ( ! defined( 'ITALYSTRAP_PLUGIN' ) or ! ITALYSTRAP_PLUGIN ) die();

/**
 * Definition array() with all the options connected to the
 * module which must be called by an include (setoptions).
 */

return array(
	'LocalBusiness'					=> __( 'Local Business - (Default)', 'italystrap' ),
	'Organization'					=> __( 'Organization - (For services and home offices)', 'italystrap' ),
	'AccountingService'				=> __( 'Accounting Service', 'italystrap' ),
	'AutoBodyShop'					=> __( 'Auto Body Shop', 'italystrap' ),
	'AutoDealer'					=> __( 'Auto Dealer', 'italystrap' ),
	'AutoPartsStore'				=> __( 'Auto Parts Store', 'italystrap' ),
	'AutoRental'					=> __( 'Auto Rental', 'italystrap' ),
	'AutoRepair'					=> __( 'Auto Repair', 'italystrap' ),
	'AutoWash'						=> __( 'Auto Wash', 'italystrap' ),
	'Attorney'						=> __( 'Attorney', 'italystrap' ),
	'Bakery'						=> __( 'Bakery', 'italystrap' ),
	'BarOrPub'						=> __( 'Bar Or Pub', 'italystrap' ),
	'BeautySalon'					=> __( 'Beauty Salon', 'italystrap' ),
	'BedAndBreakfast'				=> __( 'Bed &amp; Breakfast', 'italystrap' ),
	'BikeStore'						=> __( 'Bicycle Store', 'italystrap' ),
	'BookStore'						=> __( 'Book Store', 'italystrap' ),
	'CafeOrCoffeeShop'				=> __( 'Cafe Or Coffee Shop', 'italystrap' ),
	'ChildCare'						=> __( 'Child Care', 'italystrap' ),
	'ClothingStore'					=> __( 'Clothing Store', 'italystrap' ),
	'ComputerStore'					=> __( 'Computer Store', 'italystrap' ),
	'DaySpa'						=> __( 'Day Spa', 'italystrap' ),
	'Dentist'						=> __( 'Dentist', 'italystrap' ),
	'DryCleaningOrLaundry'			=> __( 'Dry Cleaning Or Laundry', 'italystrap' ),
	'Electrician'					=> __( 'Electrician', 'italystrap' ),
	'ElectronicsStore'				=> __( 'Electronics Store', 'italystrap' ),
	'EmergencyService'				=> __( 'Emergency Service', 'italystrap' ),
	'EntertainmentBusiness'			=> __( 'Entertainment Business', 'italystrap' ),
	'EventVenue'					=> __( 'Event Venue', 'italystrap' ),
	'ExerciseGym'					=> __( 'Exercise Gym', 'italystrap' ),
	'FinancialService'				=> __( 'Financial Service', 'italystrap' ),
	'Florist'						=> __( 'Florist', 'italystrap' ),
	'FurnitureStore'				=> __( 'Furniture Store', 'italystrap' ),
	'FoodEstablishment'				=> __( 'Food Establishment', 'italystrap' ),
	'GardenStore'					=> __( 'Garden Store', 'italystrap' ),
	'GeneralContractor'				=> __( 'General Contractor', 'italystrap' ),
	'GolfCourse'					=> __( 'Golf Course', 'italystrap' ),
	'HairSalon'						=> __( 'Hair Salon', 'italystrap' ),
	'HardwareStore'					=> __( 'Hardware Store', 'italystrap' ),
	'HealthAndBeautyBusiness'		=> __( 'Health And Beauty Business', 'italystrap' ),
	'HomeAndConstructionBusiness'	=> __( 'Home And Construction Business', 'italystrap' ),
	'HobbyShop'						=> __( 'Hobby Shop', 'italystrap' ),
	'HomeGoodsStore'				=> __( 'Home Goods Store', 'italystrap' ),
	'Hospital'						=> __( 'Hospital', 'italystrap' ),
	'Hotel'							=> __( 'Hotel', 'italystrap' ),
	'HousePainter'					=> __( 'House Painter', 'italystrap' ),
	'HVACBusiness'					=> __( 'HVAC Business', 'italystrap' ),
	'InsuranceAgency'				=> __( 'Insurance Agency', 'italystrap' ),
	'JewelryStore'					=> __( 'Jewelry Store', 'italystrap' ),
	'LiquorStore'					=> __( 'Liquor Store', 'italystrap' ),
	'Locksmith'						=> __( 'Locksmith', 'italystrap' ),
	'LodgingBusiness'				=> __( 'Lodging Business', 'italystrap' ),
	'MedicalClinic'					=> __( 'Medical Clinic', 'italystrap' ),
	'MensClothingStore'				=> __( 'Mens Clothing Store', 'italystrap' ),
	'MobilePhoneStore'				=> __( 'Mobile Phone Store', 'italystrap' ),
	'Motel'							=> __( 'Motel', 'italystrap' ),
	'MotorcycleDealer'				=> __( 'Motorcycle Dealer', 'italystrap' ),
	'MotorcycleRepair'				=> __( 'Motorcycle Repair', 'italystrap' ),
	'MovingCompany'					=> __( 'Moving Company', 'italystrap' ),
	'MusicStore'					=> __( 'Music Store', 'italystrap' ),
	'NailSalon'						=> __( 'Nail Salon', 'italystrap' ),
	'NightClub'						=> __( 'Night Club', 'italystrap' ),
	'Notary'						=> __( 'Notary Public', 'italystrap' ),
	'OfficeEquipmentStore'			=> __( 'Office Equipment Store', 'italystrap' ),
	'Optician'						=> __( 'Optician', 'italystrap' ),
	'PetStore'						=> __( 'PetStore', 'italystrap' ),
	'Physician'						=> __( 'Physician', 'italystrap' ),
	'Plumber'						=> __( 'Plumber', 'italystrap' ),
	'ProfessionalService'			=> __( 'Professional Service', 'italystrap' ),
	'RealEstateAgent'				=> __( 'Real Estate Agent', 'italystrap' ),
	'Residence'						=> __( 'Residence', 'italystrap' ),
	'Restaurant'					=> __( 'Restaurant', 'italystrap' ),
	'RoofingContractor'				=> __( 'Roofing Contractor', 'italystrap' ),
	'RVPark'						=> __( 'RV Park', 'italystrap' ),
	'School'						=> __( 'School', 'italystrap' ),
	'SelfStorage'					=> __( 'Self Storage', 'italystrap' ),
	'ShoeStore'						=> __( 'ShoeStore', 'italystrap' ),
	'SkiResort'						=> __( 'Ski Resort', 'italystrap' ),
	'SportingGoodsStore'			=> __( 'Sporting Goods Store', 'italystrap' ),
	'SportsClub'					=> __( 'Sports Club', 'italystrap' ),
	'Store'							=> __( 'Store', 'italystrap' ),
	'TattooParlor'					=> __( 'Tattoo Parlor', 'italystrap' ),
	'Taxi'							=> __( 'Taxi', 'italystrap' ),
	'TennisComplex'					=> __( 'Tennis Complex', 'italystrap' ),
	'TireShop'						=> __( 'Tire Shop', 'italystrap' ),
	'ToyStore'						=> __( 'Toy Store', 'italystrap' ),
	'TravelAgency'					=> __( 'Travel Agency', 'italystrap' ),
	'VeterinaryCare'				=> __( 'Veterinary Care', 'italystrap' ),
	'WholesaleStore'				=> __( 'Wholesale Store', 'italystrap' ),
	'Winery'						=> __( 'Winery', 'italystrap' ),
);
