name: Static Analysis

on:
  push:
    branches: [ master, Dev ]
  pull_request:
    branches: [ master, Dev ]

jobs:
  static:
    name: Static Analysis

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - uses: ramsey/composer-install@v1
        with:
          composer-options: "--prefer-dist"

      - name: PHPStan
        run: vendor/bin/phpstan analyze

#      - name: Psalm
#        run: vendor/bin/psalm