name: Unit Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    name: Test on PHP ${{ matrix.php_versions }}

    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.php_versions == '8.2' }}

    strategy:
      matrix:
        php_versions: [ '7.4', '8.0' ]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php_versions }}
        coverage: xdebug2

    - uses: ramsey/composer-install@v2
      with:
        composer-options: "--prefer-dist"

    - name: Build codeception
      run: ./vendor/bin/codecept build

    - name: Run test suite
      run: ./vendor/bin/codecept run unit --coverage-text
